--- 
author: Jesse Vincent <jesse@bestpractical.com>
distribution_type: module
generated_by: Module::Install version 0.670
license: Perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Test-OpenID-Server
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTTP::Server::Simple: 0
  Net::OpenID::Server: 0
  Test::HTTP::Server::Simple: 0
  Test::OpenID::Consumer: 0
  Test::WWW::Mechanize: 0
version: 0.02
